### ISSUE TITLE
java.lang.NullPointerException at org.lastnpe.m2e.core.configurator.ClasspathConfigurator.configure(ClasspathConfigurator.java:413)

### ISSUE THREAD

**Issue by vorburger** [lastnpe/eclipse-external-annotations-m2e-plugin#31]
I've hit this NPE while working on https://github.com/gaul/modernizer-maven-plugin/ (without any null analysis, at least not intentionally). Should hopefully be easy to guard against this?

But perhaps we should use lastNPE.org on https://github.com/lastnpe/eclipse-external-annotations-m2e-plugin? ;-) The problem, of course, is p2 VS Maven - but we probably could figure something out...

```
java.lang.NullPointerException
	at org.lastnpe.m2e.core.configurator.ClasspathConfigurator.configure(ClasspathConfigurator.java:413)
	at org.eclipse.m2e.core.project.configurator.AbstractLifecycleMapping.configure(AbstractLifecycleMapping.java:120)
	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager$3.call(ProjectConfigurationManager.java:508)
	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager$3.call(ProjectConfigurationManager.java:1)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:177)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:151)
	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager.updateProjectConfiguration(ProjectConfigurationManager.java:501)
	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager.updateProjectConfiguration0(ProjectConfigurationManager.java:439)
	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager$2.call(ProjectConfigurationManager.java:352)
	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager$2.call(ProjectConfigurationManager.java:1)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:177)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:151)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:99)
	at org.eclipse.m2e.core.internal.embedder.MavenImpl.execute(MavenImpl.java:1351)
	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager.updateProjectConfiguration(ProjectConfigurationManager.java:349)
	at org.eclipse.m2e.core.ui.internal.UpdateMavenProjectJob.runInWorkspace(UpdateMavenProjectJob.java:77)
	at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:39)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)
```

**Comment by vorburger** [comment]
The NPE seems to have something to do with `maven-compiler-plugin`'s `compilerArguments` `properties` ... in https://github.com/lastnpe/eclipse-null-eea-augments/blob/master/examples/maven/parent/pom.xml#L61 we can see that we have that, but the `org.gaul:modernizer-maven-plugin:1.7.0-SNAPSHOT` POM does not:

```
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>3.6.1</version>
        <configuration>
          <source>1.6</source>
          <target>1.6</target>
          <showDeprecation>true</showDeprecation>
          <showWarnings>true</showWarnings>
          <compilerArguments>
            <Xlint />
          </compilerArguments>
        </configuration>
      </plugin>
```

so we need an extra null check there...

**Comment by nfekete** [comment]
Eating your own dog food is always a good idea IMO. 
+1 for using null analysis + lastNPE with the plugin code
