### ISSUE TITLE
ClasspathConfigurator fails on JDK 10

### ISSUE THREAD

**Issue by jftsunami** [lastnpe/eclipse-external-annotations-m2e-plugin#37]
Version 1.0.0.201806011021

An internal cache was added to jdk.nio.zipfs.ZipFileSystemProvider, which is causing project configuration to fail after the initial configuration.

Note, this cache is also present in JDK 9

```
eclipse.buildId=4.9.0.I20180906-0745
java.version=10.0.2
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_US
Framework arguments:  -product org.eclipse.epp.package.jee.product
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -product org.eclipse.epp.package.jee.product
```
```
java.nio.file.FileSystemAlreadyExistsException
	at jdk.zipfs/jdk.nio.zipfs.ZipFileSystemProvider.newFileSystem(ZipFileSystemProvider.java:99)
	at java.base/java.nio.file.FileSystems.newFileSystem(FileSystems.java:344)
	at java.base/java.nio.file.FileSystems.newFileSystem(FileSystems.java:293)
	at org.lastnpe.m2e.core.configurator.ClasspathConfigurator.read(ClasspathConfigurator.java:174)
	at org.lastnpe.m2e.core.configurator.ClasspathConfigurator.readLines(ClasspathConfigurator.java:133)
	at org.lastnpe.m2e.core.configurator.ClasspathConfigurator.getExternalAnnotationMapping(ClasspathConfigurator.java:117)
	at org.lastnpe.m2e.core.configurator.ClasspathConfigurator.lambda$3(ClasspathConfigurator.java:110)
	at java.base/java.util.Optional.ifPresent(Optional.java:172)
	at org.lastnpe.m2e.core.configurator.ClasspathConfigurator.getExternalAnnotationMapping(ClasspathConfigurator.java:109)
	at org.lastnpe.m2e.core.configurator.ClasspathConfigurator.configureClasspath(ClasspathConfigurator.java:86)
	at org.eclipse.m2e.jdt.internal.DefaultClasspathManagerDelegate.populateClasspath(DefaultClasspathManagerDelegate.java:65)
	at org.eclipse.m2e.jdt.internal.BuildPathManager.getClasspath(BuildPathManager.java:267)
	at org.eclipse.m2e.jdt.internal.BuildPathManager.getClasspath(BuildPathManager.java:384)
	at org.eclipse.m2e.jdt.internal.BuildPathManager.getClasspath(BuildPathManager.java:364)
	at org.eclipse.m2e.jdt.internal.BuildPathManager.getClasspath(BuildPathManager.java:392)
	at org.eclipse.m2e.jdt.internal.BuildPathManager.updateClasspath(BuildPathManager.java:205)
	at org.eclipse.m2e.jdt.internal.BuildPathManager.mavenProjectChanged(BuildPathManager.java:194)
	at org.eclipse.m2e.core.internal.project.registry.ProjectRegistryManager.notifyProjectChangeListeners(ProjectRegistryManager.java:783)
	at org.eclipse.m2e.core.internal.project.registry.ProjectRegistryManager.applyMutableProjectRegistry(ProjectRegistryManager.java:930)
	at org.eclipse.m2e.core.internal.project.registry.ProjectRegistryManager.refresh(ProjectRegistryManager.java:300)
	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager.updateProjectConfiguration0(ProjectConfigurationManager.java:405)
	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager$2.call(ProjectConfigurationManager.java:352)
	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager$2.call(ProjectConfigurationManager.java:1)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:177)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:151)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:99)
	at org.eclipse.m2e.core.internal.embedder.MavenImpl.execute(MavenImpl.java:1351)
	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager.updateProjectConfiguration(ProjectConfigurationManager.java:349)
	at org.eclipse.m2e.core.ui.internal.UpdateMavenProjectJob.runInWorkspace(UpdateMavenProjectJob.java:77)
	at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:42)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

**Comment by vorburger** [comment]
Would you be willing to raise a Pull Request which fixes this problem, to
give back to this project which is apparently providing some value to you?

**Comment by jftsunami** [comment]
Sure.  I just had to get permission to work on and release code from my employers.

**Comment by jftsunami** [comment]
I couldn't replicate the problem using JUnit, but the built plugin slots into my setup of Eclipse 2018-09 running JDK-10 and configures the path for java:java.

#38

**Comment by jftsunami** [comment]
Put together a smaller patch set to just address the issue I ran into without trying to create a testing project, #39

**Comment by vorburger** [comment]
Hm, interesting issue... :smiley: I did a quick search, and it seems we were not the only ones confused re. `java.nio.file.FileSystems.newFileSystem()` (VS `getFileSystem()`), see e.g. https://github.com/pf4j/pf4j/issues/96#issuecomment-198703263 or https://bugs.eclipse.org/bugs/show_bug.cgi?id=539139. I've not read those two issues in full details, or searched further, to understand if there would be a better fix - but just ditching it and instead just falling back to using `java.util.zip.ZipFile` and `java.util.zip.ZipEntry` like you do in #39 seems totally "fair" to me  here - so merged! :smile: 

Thank you for contributing.

**Comment by jftsunami** [comment]
You're welcome.
